version: '3.8'

services:
  adk-voice-agent:
    image: spb722/apex:adk-voice-agent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Ensure the app binds to all interfaces
      - HOST=0.0.0.0
      - PORT=8000
      # Pass Google API key from environment or .env file
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Set Google application credentials path
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      # Mount the app directory for development (hot reload)
      - ./app:/app/app:rw
      # Mount credentials and environment files (read-only)
      - ./credentials.json:/app/credentials.json:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s